config/routes.rb
Rails.application.routes.draw do
  get 'quiz/show'

  devise_for :users, :controllers => { :omniauth_callbacks => "user/omniauth_callbacks", registrations: "registrations" }

  root 'home#connexion'
  #root 'home#index'
  get 'connexion' => 'home#connexion'
  get 'profil' => 'users#profil'
  get 'chat' => 'users#chat'
  get 'chatAdmin' => 'users#chatAdmin'

  resources :conversations, only: [:create] do
    member do
      post :close
    end
    resources :messages, only: [:create]
  end
  #devise_scope :user do
  #  root to: "devise/sessions#new"
  #end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :messages
  has_many :conversations, foreign_key: :sender_id
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  validates :nom, :prenom, presence: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  devise :omniauthable, :omniauth_providers => [:linkedin]

  def self.from_omniauth(auth)
  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
    user.email = auth.info.email
    user.password = Devise.friendly_token[0,20]
    user.nom = auth.info.last_name
    user.prenom = auth.info.first_name   # assuming the user model has a name
    #user.image = auth.info.image # assuming the user model has an image
    # If you are using confirmable and the provider(s) you use validate emails,
    # uncomment the line below to skip the confirmation emails.
    # user.skip_confirmation!
    end
  end

  def self.from_linkedin(auth)

    where(linkedin_id: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.nom = auth.info.last_name
      user.prenom = auth.info.first_name
      user.provider = auth.provider
      user.uid = auth.uid
      user.password = Devise.friendly_token[0, 20]
      user.skip_confirmation!
    end

  end




end

app/controllers/User/confirmations_controller.rb
class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/User/omniauth_callbacks_controller.rb
class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

 def linkedin
   @user = User.from_linkedin(request.env['omniauth.auth'])
   if @user.persisted?
     sign_in_and_redirect @user, event: :authentication
   else
     session['devise.linkedin'] = request.env['omniauth.auth'].except("extra")
     redirect_to new_user_registration_url
   end

end

 def failure
   redirect_to root_path
 end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/User/passwords_controller.rb
class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/User/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
   def create
     super
     puts "coucoucou"
   end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/User/sessions_controller.rb
class User::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/User/unlocks_controller.rb
class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def profil
  end

  def chat
    session[:conversations] ||= []

    @users = User.all.where(email: "marc@hotmail.fr")
    @conversations = Conversation.where(recipient: 3)
  end

  def chatAdmin
    session[:conversations] ||= []

    @users = User.all.where.not(id: current_user)
    @conversations = Conversation.includes(:recipient, :messages)
                                 .find(session[:conversations])
  end



end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/chat.html.erb
<div class="main" id="mainProfil">

  <div class="containerTitle" id="containerTitleProfil">
    <div class="containerMarc">
      <div class="roundedImage" class="photoMarc"><%= image_tag("sangoku.jpg", id: "imageProfil") %></div>
    </div>
    <div class="containerUser">
      <div class="roundedImage" class="photoUser"><%= image_tag("vegeta.jpg", id: "imageProfil") %></div>
    </div>
  </div>

  <div class=containerProfil>
    <div class="row">
      <div class="col-md-12">
        <ul id="conversations-list">
          <% @conversations.each do |conversation| %>
            <%= render 'conversations/conversationTest', conversation: conversation, user: current_user %>
          <% end %>
        </ul>
      </div>

    </div>

    </div>



    <div class="empty">

    </div>

    <div class=onglets>
      <%= link_to chat_path do %>
        <div class=ongletChat2><%= image_tag("iconeChat2.png", id: "iconeChat") %></div>
      <% end %>
      <%= link_to profil_path do %>
        <div class=ongletProfil2><%= image_tag("iconeProfil2.png", id: "iconeProfil") %></div>
      <% end %>
    </div>

  </div>

</div>

app/views/users/chatAdmin.html.erb
<div class="main" id="mainProfil">

  <div class="containerTitle" id="containerTitleProfil">
    <div class="containerMarc">
      <div class="roundedImage" class="photoMarc"><%= image_tag("sangoku.jpg", id: "imageProfil") %></div>
    </div>
    <div class="containerUser">
      <div class="roundedImage" class="photoUser"><%= image_tag("vegeta.jpg", id: "imageProfil") %></div>
    </div>
  </div>

  <div class=containerProfil>
    <div class="row">
      <div class="col-md-9">
        <ul id="conversations-list">
          <% @conversations.each do |conversation| %>
            <%= render 'conversations/conversation', conversation: conversation, user: current_user %>
          <% end %>
        </ul>
      </div>

      <div class="col-md-3">
        <div class="panel panel-primary">
          <div class="panel-heading">
            <h3 class="panel-title">User list</h3>
          </div>
          <div class="panel-body">
            <ul>
              <% @users.each do |user| %>
                <li><%= link_to user.email, conversations_path(user_id: user), remote: true, method: :post %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>

    </div>

    <div class="empty">

    </div>

    <div class=onglets>
      <%= link_to chat_path do %>
        <div class=ongletChat2><%= image_tag("iconeChat2.png", id: "iconeChat") %></div>
      <% end %>
      <%= link_to profil_path do %>
        <div class=ongletProfil2><%= image_tag("iconeProfil2.png", id: "iconeProfil") %></div>
      <% end %>
    </div>

  </div>

</div>

app/views/users/profil.html.erb
<div id="mainProfil">

  <div class="containerTitle" id="containerTitleProfil">
    <div class="containerPhoto" id="containerPhoto">
      <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="true"><div class="roundedImage"><%= image_tag("vegeta.jpg", id: "imageProfil") %></div> </a>
                    <ul class="dropdown-menu">
                      <li><a href="#"><div class="logOut"><%= link_to "Log out", destroy_user_session_path, method: :delete %></div></a></li>
                    </ul>
                  </li>
    </div>
    <div class=iconEdit><%= link_to image_tag("edit.png", id: "iconEdit2"), edit_user_registration_path %></div>
  </div>

  <div class=containerProfil>
    <p class=nameProfil><%= current_user.prenom %> <%= current_user.nom %></p>

    <div class=interets>
      <div class=titleSkills><p class=titleSkills2>ℹ️ Informations</p> </div> </br>
      <p>27 ans</p>
      <p>Responsable Marketing</p>
      <p><%= current_user.email %></p>
    </div>

    <div class=skills>
      <div class=iconeSkills> <%= image_tag("etoile.png", id: "iconeSkills") %> </div>
      <div class=titleSkills><p class=titleSkills2> Compétences</p> </div> </br>
      <p>#HTML #CSS #Boxe</p>
    </div>

    <div class=love>
      <div class=iconeLove> <%= image_tag("coeur.png", id: "iconeLove") %> </div>
      <div class=titleLove><p class=titleLove2> Intérêts</p> </div> </br>
      <p>#JavaScript #Tennis #Entrepreneuriat</p>
    </div>

    <div class="empty">

    </div>

    <div class=onglets>
        <%= link_to chat_path do %>
      <div class=ongletChat><%= image_tag("iconeChat2.png", id: "iconeChat") %></div>
      <% end %>
        <div class=ongletProfil><%= image_tag("iconeProfil2.png", id: "iconeProfil") %></div>
    </div>

  </div>

</div>