config/routes.rb
Rails.application.routes.draw do
  get 'quiz/show'

  devise_for :users, :controllers => { :omniauth_callbacks => "user/omniauth_callbacks", registrations: "registrations" }

  root 'home#connexion'
  #root 'home#index'
  get 'connexion' => 'home#connexion'
  get 'profil' => 'users#profil'
  get 'chat' => 'users#chat'
  get 'chatAdmin' => 'users#chatAdmin'

  resources :conversations, only: [:create] do
    member do
      post :close
    end
    resources :messages, only: [:create]
  end
  #devise_scope :user do
  #  root to: "devise/sessions#new"
  #end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def connexion
    if user_signed_in?
       redirect_to profil_path
     else
       root_path
    end
  end

  def index
   session[:conversations] ||= []

   @users = User.all.where.not(id: current_user)
   @conversations = Conversation.includes(:recipient, :messages)
                                .find(session[:conversations])
 end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/connexion.html.erb
<body id="home">
  <div class="mainhome">
    <nav class="navbar">
      <div class="navigation">
        <div id=logohome>
          <%= image_tag("logo.png", id: "logo1")%>
        </div>
        <div class="log">

          <%= link_to "Sign in",   new_user_registration_path, :class => "buttonsignin"%>
        </div>
      </nav>

      <div class="content">
        <div class="main-carousel" data-flickity='{ "autoPlay": 3000, "pauseAutoPlayOnHover": false, "wrapAround": true, "imagesLoaded": true}'>
          <div class="carousel-cell"><%= image_tag("img/img3.jpg")%></div>
          <div class="carousel-cell"><%= image_tag("img/img2.jpg")%></div>
          <div class="carousel-cell"><%= image_tag("img/img4.jpg")%></div>
        </div>
      </div>
      <div class="section">

        <div class="button">
          <%= link_to "Cliquez ici pour commencer !",  quiz_show_path, :class => "buttonstart", method: :get%>
        </div>
      </div>
    </div>
  </body>

app/views/home/index.html.erb
<div class="row">
  <div class="col-md-9">
    <ul id="conversations-list">
      <% @conversations.each do |conversation| %>
        <%= render 'conversations/conversation', conversation: conversation, user: current_user %>
      <% end %>
    </ul>
  </div>

  <div class="col-md-3">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">User list</h3>
      </div>
      <div class="panel-body">
        <ul>
          <% @users.each do |user| %>
            <li><%= link_to user.email, conversations_path(user_id: user), remote: true, method: :post %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>